charts/codeveros-user-service/Chart.yaml, charts/codeveros-user-service/templates/deployment.yaml, charts/codeveros-user-service/templates/tests/test-connection.yaml, charts/codeveros-user-service/values.yaml
=> update user service chart

charts/codeveros-training-service/Chart.yaml, charts/codeveros-training-service/templates/deployment.yaml, charts/codeveros-training-service/templates/tests/test-connection.yaml, charts/codeveros-training-service/values.yaml
=> update training service chart

charts/codeveros-gateway/Chart.yaml, charts/codeveros-gateway/templates/NOTES.txt, charts/codeveros-gateway/templates/_helpers.tpl, charts/codeveros-gateway/templates/deployment.yaml, charts/codeveros-gateway/templates/service.yaml, charts/codeveros-gateway/templates/tests/test-connection.yaml, charts/codeveros-gateway/values.yaml
=> add gateway chart

.github/workflows/release-charts.yaml
=> add chart release workflow

charts/codeveros/Chart.yaml, charts/codeveros/templates/_helpers.tpl, charts/codeveros/templates/configmap.yaml, charts/codeveros/templates/deployment.yaml, charts/codeveros/templates/ingress.yaml, charts/codeveros/templates/service.yaml, charts/codeveros/templates/tests/test-proxy.yaml, charts/codeveros/values.yaml, ct.yaml
=> initial commit of codeveros chart

charts/codeveros-auth-service/Chart.yaml, charts/codeveros-auth-service/values.yaml, charts/codeveros-gateway/Chart.yaml, charts/codeveros-gateway/values.yaml, charts/codeveros-training-service/Chart.yaml, charts/codeveros-training-service/values.yaml, charts/codeveros-ui/Chart.yaml, charts/codeveros-ui/values.yaml, charts/codeveros-user-service/Chart.yaml, charts/codeveros-user-service/values.yaml
=> change chart pull policy to ifnotpresent

services/auth-service/nodejs/package-lock.json, services/auth-service/nodejs/package.json, services/training-service/nodejs/package-lock.json, services/training-service/nodejs/package.json, services/user-service/nodejs/package-lock.json, services/user-service/nodejs/package.json
=> update services to latest codeveros-ms dependency

services/auth-service/nodejs/package-lock.json, services/auth-service/nodejs/package.json, services/gateway/nodejs/package-lock.json, services/gateway/nodejs/package.json, services/training-service/nodejs/package-lock.json, services/training-service/nodejs/package.json, services/user-service/nodejs/package-lock.json, services/user-service/nodejs/package.json
=> update dependencies to resolve dependabot alerts

charts/codeveros/Chart.yaml
=> update codeveros chart

.github/workflows/auth-service.yml, .github/workflows/gateway.yml, .github/workflows/training-service.yml, .github/workflows/ui.yml, .github/workflows/user-service.yml
=> update service ci workflows

.github/workflows/release-charts.yaml
Remove adding deprecated stable repo, limit execution to chart/** path changes
=> Correct chart release workflow

services/auth-service/nodejs/package-lock.json, services/auth-service/nodejs/package.json, services/auth-service/package-lock.json, services/training-service/nodejs/package-lock.json, services/training-service/nodejs/package.json, services/user-service/nodejs/package-lock.json, services/user-service/nodejs/package.json
=> update codeveros-ms dependency for auth, training, and user service

services/auth-service/nodejs/Dockerfile, services/gateway/nodejs/Dockerfile, services/training-service/nodejs/Dockerfile, services/ui/angular/Dockerfile.multistage, services/user-service/nodejs/Dockerfile
=> update base node container used by services to 14.x

.github/workflows/release-charts.yaml, .github/workflows/test-charts.yml, charts/codeveros-auth-service/Chart.yaml, charts/codeveros-gateway/Chart.yaml, charts/codeveros-training-service/Chart.yaml, charts/codeveros-training-service/values.yaml, charts/codeveros-ui/Chart.yaml, charts/codeveros-user-service/Chart.yaml, charts/codeveros-user-service/values.yaml, ct.yaml
=> update service images used in charts and mongodb chart dependencies

charts/codeveros/Chart.yaml
=> update codeveros umbrella chart with latest service versions

charts/codeveros-gateway/Chart.yaml, charts/codeveros-gateway/templates/ingress.yaml, charts/codeveros-gateway/values.yaml, charts/codeveros-ui/Chart.yaml, charts/codeveros-ui/templates/ingress.yaml, charts/codeveros-ui/values.yaml, charts/codeveros/templates/ingress.yaml
=> charts: add ingress to codeveros-ui and codeveros-gateway charts

charts/codeveros-gateway/Chart.yaml, charts/codeveros-gateway/README.md, charts/codeveros-gateway/templates/ingress.yaml, charts/codeveros-gateway/values.yaml, charts/codeveros-ui/Chart.yaml, charts/codeveros-ui/README.md, charts/codeveros-ui/templates/ingress.yaml, charts/codeveros-ui/values.yaml
=> add tls option to ui and gateway charts

charts/codeveros-gateway/Chart.yaml, charts/codeveros-gateway/templates/ingress.yaml, charts/codeveros-gateway/values.yaml, charts/codeveros-ui/Chart.yaml, charts/codeveros-ui/templates/ingress.yaml, charts/codeveros-ui/values.yaml
=> make ingress paths configurable to support aws load balancer

.github/workflows/label.yml
Use pull_request_target instead of pull_request
=> Fix Labeler action on Dependabot PRs

.github/workflows/release-charts.yaml, .github/workflows/test-charts.yml, README.md, charts/codeveros-auth-service/README.md, charts/codeveros-gateway/README.md, charts/codeveros-training-service/README.md, charts/codeveros-ui/README.md, charts/codeveros-user-service/README.md, services/auth-service/README.md, services/gateway/README.md, services/gateway/nodejs/README.md, services/gateway/nodejs/src/lib/api-docs.js, services/training-service/README.md, services/training-service/nodejs/README.md, services/training-service/nodejs/src/swagger.yaml, services/ui/angular/package.json, services/ui/angular/src/app/welcome/welcome.component.html, services/user-service/README.md, services/user-service/nodejs/README.md, services/user-service/nodejs/src/swagger.yaml, tests/selenified/src/test/java/com/coveros/codeveros/pom/MainPage.java
=> docs: fix casing

services/ui/angular/package.json
This allows the angular service to listen for requests outside localhost and on multiple interfaces.
=> NOREF: fix localhost resolution problems with UI angular host

.gitignore, exercises/1-insufficient-quota/README.md, exercises/1-insufficient-quota/pod-quota.yml, exercises/2-limit-ranges/README.md, exercises/2-limit-ranges/limit-range.yml, exercises/3-failing-probes/README.md, exercises/4-image-pull/README.md
K8s Troubleshooting exercises for common failures.
=> NOREF: added troubleshooting exercises
